using System;
using System.Collections;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;


public class SpeechBubbleGen : MonoBehaviour
{
    public Bubble bubble;

    [Tooltip("The adioclip generated by the CoquiTTS generator")]
    [AssetPath.Attribute(typeof(AudioClip))]
    public string clip;

    private AudioClip audioClip;
    private TextAsset textJSON;
    private string metaPath;

	// Start is called before the first frame update
	void Start()
    {
        GetMeta();
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public void Generate()
    {
		audioClip = AssetPath.Load<AudioClip>(clip);
	}

    public void GetMeta()
    {
        bubble = new Bubble();
        int lastSlash = clip.Length - Reverse(clip).IndexOf("/");
		metaPath = clip.Substring(0, lastSlash) + "meta_" + clip.Substring(lastSlash, clip.IndexOf(".", lastSlash) - lastSlash) + ".json";
        textJSON = AssetPath.Load<TextAsset>(metaPath);
		bubble = JsonUtility.FromJson<Bubble>(textJSON.text);
	}

	public static string Reverse(string s)
	{
		char[] charArray = s.ToCharArray();
		Array.Reverse(charArray);
		return new string(charArray);
	}
}
